### ISSUE TITLE
AttributeError: 'module' object has no attribute 'img_b64_to_array'

### ISSUE THREAD

**Issue by SiDinhThoi** [fengzhongyouxia/TensorExpand#9]
When I run python labelme2COCO.py, I have a following bug:
Traceback (most recent call last):
  File "labelme2COCO.py", line 144, in <module>
    labelme2coco(labelme_json,'new.json')
  File "labelme2COCO.py", line 31, in __init__
    self.save_json()
  File "labelme2COCO.py", line 136, in save_json
    self.data_transfer()
  File "labelme2COCO.py", line 37, in data_transfer
    self.images.append(self.image(data,num))
  File "labelme2COCO.py", line 49, in image
    img = utils.img_b64_to_array(data['imageData'])

I don't know how to fix this error, help me

**Comment by ll884856** [comment]
Have you solved this problem? I have the same problem. Thanks.

**Comment by SiDinhThoi** [comment]
Hi,

My OS is Ubuntu 16.04 and I try to install labelme with Python2 and the error was fixed:
# Ubuntu 14.04 / Ubuntu 16.04
# Python2
# sudo apt-get install python-qt4  # PyQt4
sudo apt-get install python-pyqt5  # PyQt5
sudo pip install labelme

**Comment by shaolei-wang** [comment]
On the code, it uses
```
from .image import img_arr_to_b64
from .image import img_b64_to_arr
```
So you need change `img_b64_to_array` to `img_b64_to_arr`

**Comment by hundundragonsoul** [comment]
> On the code, it uses
> 
> ```
> from .image import img_arr_to_b64
> from .image import img_b64_to_arr
> ```
> So you need change `img_b64_to_array` to `img_b64_to_arr`

Thanks for your help!

**Comment by LIMU2** [comment]
> On the code, it uses
> 
> ```
> from .image import img_arr_to_b64
> from .image import img_b64_to_arr
> ```
> 
> So you need change `img_b64_to_array` to `img_b64_to_arr`

thx~ it's really helpful

**Comment by AbdullahJirjees** [comment]
@SiDinhThoi  I have you same issue, I tried to code on Windows 11, and on Ubuntu, I got the same issue. Can you please help me with how did you solve the issue? 
Thanks
